dnf -y install 'dnf-command(copr)'
dnf -y copr enable @python/python3.8 
sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/_copr*.repo
sed -i 's/enabled=1/enabled=0/g' /etc/yum.repos.d/fedora-rawhide*.repo
dnf -y update python3
sed -i '0,/enabled=0/s//enabled=1/g' /etc/yum.repos.d/fedora-rawhide*.repo
dnf -y builddep scipy
dnf -y install python3-Cython vim gdb fedora-packager
fedpkg clone --anonymous scipy
cd scipy
fedpkg prep
cd scipy-1.2.1
rm -f $(grep -rl '/\* Generated by Cython') PKG-INFO
python3 setup.py build

